deployment

diff --git a/.github/workflows/eks-deploy.yaml b/.github/workflows/eks-deploy.yaml
--- a/.github/workflows/eks-deploy.yaml
+++ b/.github/workflows/eks-deploy.yaml
@@ -99,7 +99,7 @@ jobs:
           version: v3.14.0
       - name: uninstall backend helm chart
         run: |
-          helm uninstall backend-app -n default || echo "Release not found, skipping uninstall"
+          helm uninstall frontend-app -n default || echo "Release not found, skipping uninstall"
 
       - name: Deploy Helm chart
         run: |
