deployment

diff --git a/.github/workflows/eks-deploy.yaml b/.github/workflows/eks-deploy.yaml
--- a/.github/workflows/eks-deploy.yaml
+++ b/.github/workflows/eks-deploy.yaml
@@ -50,6 +50,9 @@ jobs:
         uses: azure/setup-helm@v3
         with:
           version: v3.14.0
+      - name: uninstall backend helm chart
+        run: |
+          helm uninstall backend-app -n default || echo "Release not found, skipping uninstall"
 
       - name: Deploy Helm chart
         run: |
